name: Deploy AWS Resources

on:
    push:
      branches:
        - uat*
        - ma*
    pull_request:
      branches:
        - prod*
        - uat*
        - ma*
      types:
        - closed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
                
            - name: Check out code
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.6.0 

            - name: Fetch Terraform modules
              run: terraform init
            
            - name: Terraform Validate
              run: terraform validate
            #   uses: hashicorp/terraform-github-actions/validate@v0.3.7
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #     # TF_ACTION_WORKING_DIR: 'terraform'
            #     AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            # - name: Run Terraform apply
            #   run: terraform apply -var "region=us-east-1" -var "vpc_name=Application-Vpc" -auto-approve
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #     TF_ACTION_WORKING_DIR: 'terraform'secrets
            #     AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: Terraform Plan
              run: terraform plan
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                # TF_ACTION_WORKING_DIR: 'terraform'
                AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Terraform Apply
              run: terraform apply -auto-approve
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    # TF_ACTION_WORKING_DIR: 'terraform'
                    AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

                #  
            #   uses: hashicorp/terraform-github-actions/apply@v0.4.0
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #     TF_ACTION_WORKING_DIR: 'terraform'
            #     AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            