name: Deploy AWS Resources

on:
    push:
      branches:
        - uat
        - test
    pull_request:
      branches:
        - prod
        - uat
        - test
      types:
        - closed

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{github.ref_name}}

        defaults:
          run:
            working-directory: ./terraform
        
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
              #   sparse-checkout: |
              #         terraform
                fetch-depth: 2
                submodules: true
            - name: Set AWS Region
              run: echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
    
            - name: Display AWS Region
              run: echo "AWS Region = $AWS_REGION"
      
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.6.0 

            - name: Fetch Terraform modules
              run: terraform init
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}

            - name: Terraform Validate
              run: terraform validate
            
            - name: Terraform Plan
              run: terraform plan -var "aws_region=${AWS_REGION}"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}

            - name: Terraform Apply
              run: terraform apply -auto-approve -var="aws_region=${{ secrets.AWS_REGION }}"
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_REGION: ${{ secrets.AWS_REGION }}
