name: Build and Upload Wheel

on:
  push:
    branches: [ test_1 ]


jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{github.ref_name}}

    defaults:
      run:
        shell: bash
        working-directory: ./scripts

    steps:
      - uses: actions/checkout@v2

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate  # Activate virtual environment

      - name: Install build tools
        run: |
          pip install --upgrade setuptools wheel build

      - name: Build wheel
        run: |
          python -m build

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload wheel to S3
        run: |
          aws s3 cp --recursive ./dist s3://program-assessment/apps/
