name: Deploy AWS Resources

on:
    workflow_dispatch:
      inputs:
        region:
          description: 'Region'
          required: true
          default: 'us-east-1'
        vpc:
          description: 'VPC Name'
          required: true
          default: 'Application-Vpc'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
                
            - name: Check out code
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.2.8    

            - name: Fetch Terraform modules
              run: terraform init
            
            - name: Terraform Validate
              uses: hashicorp/terraform-github-actions/validate@v0.3.7
        
            - name: Run Terraform apply
              run: terraform apply -var "region=${{ github.event.inputs.region }}" -var "vpc_name=${{ github.event.inputs.vpc }}" -auto-approve
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                TF_ACTION_WORKING_DIR: 'terraform'
                AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        