name: Building Docker Image
on:
    push:
      branches: [ test ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      AWS_REGION: us-east-1
      AWS_ECR_REPO: dummy_ecr
      AWS_ACCOUNT_ID : 050223225208
      lambda_func : test_lambda
      slack_webhook: ${{secrets.SLACK_WEBHOOK_URL}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
   

      - name: Set environment variables
        run: |
          if [[ ${{ github.ref }} == refs/heads/test ]]; then
            echo "Environment=uat" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == refs/heads/master ]]; then
            echo "Environment=prod" >> $GITHUB_ENV
          fi

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2

      # - name: Build, tag, and push image to Amazon ECR
      #   id: build-image
      #   run: |
      #     source version_track.sh
      # - name: Set up environment
      #   run: echo "ECR_IMAGE_TAG=$(cat .env | grep ECR_IMAGE_TAG | cut -d'=' -f2)" >> $GITHUB_ENV

      # - name: Push-ECR
      #   env: 
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: $AWS_ECR_REPO
      #     IMAGE_TAG: ${{ env.ECR_IMAGE_TAG }}
      #   run: |
      #     docker build --build-arg env=${{ env.Environment }} \
      #       -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .  
      #     docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      #     echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up environment
        run: echo "ECR_IMAGE_TAG=$(cat env | grep ECR_IMAGE_TAG | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
          
      # - name: Push-ECR
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: ${{ env.AWS_ECR_REPO }}
      #     IMAGE_TAG: ${{ env.ECR_IMAGE_TAG }}
      #   run: |
      #       source version_track.sh
      #       docker build --build-arg AWS_REGION=${{ vars.AWS_REGION }} \
      #         --build-arg AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} \
      #         -t $REGISTRY/$REPOSITORY:$VERSION .  
      #       docker push $REGISTRY/$REPOSITORY:$VERSION
      # #       echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update lambda Job Definition
        id: modify_job_def
        run : |
          source version_track.sh
          aws lambda update-function-code --function-name $lambda_func --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_ECR_REPO:${VERSION}

      # - name: Update lambda Job Definition
      #   id: modify_job_def
      #   run : |
      #     source version_track.sh
      #     aws lambda update-function-code --function-name $lambda_func --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_ECR_REPO:${VERSION}
  