name: Reusable Workflow
on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      input1:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # Use the calling repository
          token: ${{ secrets.token }}
          fetch-depth: 0 
  
      - name: List files
        run: ls -la

      - name: pwd
        run: pwd

      - name: Run sample script
        run: |
            echo "Running with input: ${{ inputs.input1 }}"
            chmod +x test_run.sh
            ./test_run.sh
