name: Reusable Workflow
on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          repository: Anuhya27/workflow_sample  # Ensure this is correct
          token: ${{ secrets.GITHUB_TOKEN }}  # Use PAT for private repos
          ref: "test"
  
      - name: List files
        run: ls -la

      - name: Run sample script
        run: |
            echo "Running with input: ${{ inputs.input1 }}"
            chmod +x test_run.sh
            ./test_run.sh
